// Console messages
console.log("Portfolio loaded!");
console.log("Student: Ahmed Abdelhamid");
console.log("JavaScript running!");

// State variable
let isDark = false;

// On page load - read theme from localStorage
window.onload = function() {
    const savedTheme = localStorage.getItem("portfolio_theme");
    if (savedTheme === "dark") {
        isDark = true;
        document.body.classList.add("dark");
        console.log("Dark theme loaded from localStorage");
    }

    // Last updated date - generated by JavaScript
    const today = new Date();
    const formatted = today.toISOString().split("T")[0];
    document.getElementById("last-updated").textContent = "Last updated: " + formatted;
};

// Theme toggle function
function toggleTheme() {
    isDark = !isDark;
    document.body.classList.toggle("dark");

    // Save to localStorage
    if (isDark) {
        localStorage.setItem("portfolio_theme", "dark");
        console.log("Theme switched to dark");
    } else {
        localStorage.setItem("portfolio_theme", "light");
        console.log("Theme switched to light");
    }
}
