// Console messages
console.log("Portfolio loaded!");
console.log("Student: Ahmed Abdelhamid");
console.log("JavaScript running!");

// State variable
let isDark = false;

// On page load
window.onload = function() {
    // Read theme from localStorage
    const savedTheme = localStorage.getItem("portfolio_theme");
    if (savedTheme === "dark") {
        isDark = true;
        document.body.classList.add("dark");
        console.log("Dark theme loaded from localStorage");
    }

    // Last updated date - generated by JavaScript
    const today = new Date();
    const formatted = today.toISOString().split("T")[0];
    document.getElementById("last-updated").textContent = "Last updated: " + formatted;
};

// Theme toggle function
function toggleTheme() {
    isDark = !isDark;
    document.body.classList.toggle("dark");

    if (isDark) {
        localStorage.setItem("portfolio_theme", "dark");
        console.log("Theme switched to dark");
    } else {
        localStorage.setItem("portfolio_theme", "light");
        console.log("Theme switched to light");
    }
}

// Why do we use async/await?
// Because it makes asynchronous code easier to read and write,
// it lets us wait for the fetch to finish before moving on.

// Why do we check response.ok?
// Because fetch() does not throw an error for bad responses like 404.
// We need to check manually if the response was successful.

// Why do we use try/catch?
// To handle errors gracefully. If something goes wrong (network issue etc),
// the catch block will run instead of crashing the page.

async function loadData() {
    const display = document.getElementById("data-display");

    // Show loading message
    display.textContent = "Loading...";

    try {
        // Fetch data from API
        const response = await fetch("https://jsonplaceholder.typicode.com/users/1");

        // Check if response is ok
        if (!response.ok) {
            throw new Error("Response was not ok");
        }

        // Convert to JSON
        const user = await response.json();

        // Update the DOM dynamically
        display.innerHTML = `
            <div class="card">
                <h3>User Info</h3>
                <p><strong>Name:</strong> ${user.name}</p>
                <p><strong>Email:</strong> ${user.email}</p>
                <p><strong>Company:</strong> ${user.company.name}</p>
            </div>
        `;

        console.log("Data loaded successfully:", user.name);

    } catch (error) {
        display.textContent = "Error loading data";
        console.log("Error:", error);
    }
}
